### ISSUE TITLE
Exception: process 0 terminated with signal SIGABRT

### ISSUE THREAD

**Issue by JCBrouwer** [podgorskiy/ALAE#15]
Hello, I'm trying to get this running in a conda environment and running into SIGABRT when starting training.

I've installed all the listed dependencies and created the tfrecords for my dataset by modifying prepare_celeba_hq_tfrecords.py to grab images from my own folder instead. This all seemed to go fine, but when training I get the following error:

```
Traceback (most recent call last):
  File "train_alae.py", line 375, in <module>
    run(train, get_cfg_defaults(), description="StyleGAN", default_config="configs/ffhq.yaml", world_size=gpu_count)
  File "/home/hans/code/ALAE/launcher.py", line 122, in run
    mp.spawn(_run, args=(world_size, fn, defaults, write_log, no_cuda, args), nprocs=world_size, join=True)
  File "/home/hans/.conda/envs/alae/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hans/.conda/envs/alae/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/hans/.conda/envs/alae/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGABRT
```
The traceback isn't very useful, but I believe it's happening on the `model.train()` call just before `for x_orig in tqdm(batches):` in `train_alae.py`.

I'm running this on Ubuntu 18.10 with 2x1080Ti GPUs with NVidia driver version: 435.21 / CUDA version: 10.1.

I've tried installing cudatoolkit=9.0 with conda, but then the environment can only solve up to pytorch=1.1. With cudatoolkit=9.2 I was able to get pytorch=1.3, but with the same result.

My conda env:
```
# packages in environment at /home/hans/.conda/envs/alae:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py36_0  
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                   pypi_0    pypi
dareblopy                 0.0.2                    pypi_0    pypi
dlutils                   0.0.12                   pypi_0    pypi
dnnlib                    0.0.1                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
intel-openmp              2020.0                      166  
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
markdown                  3.2.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2020.0                      166  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
ncurses                   6.2                  he6710b0_0  
ninja                     1.9.0            py36hfd86e86_0  
numpy                     1.14.5                   pypi_0    pypi
olefile                   0.46                     py36_0  
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.3                     pypi_0    pypi
pillow                    7.0.0            py36hb39fc2d_0  
pip                       20.0.2                   py36_1  
protobuf                  3.11.3                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.10               hcf32534_1  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.5.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                39.1.0                   pypi_0    pypi
six                       1.14.0                   py36_0  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.31.1               h62c20be_1  
tensorboard               1.10.0                   pypi_0    pypi
tensorflow-gpu            1.10.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
torchvision               0.6.0                py36_cu101    pytorch
tqdm                      4.45.0                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.7                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

**Comment by podgorskiy** [comment]
For training, cudatoolkit is irrelevant, since pytorch is statically linked to CUDA runtime.
Older cudatoolkit is needed to run evaluation only.
Try running in single GPU mode, it will give you a better stack trace.

The problem is most likely related to https://github.com/podgorskiy/DareBlopy .
It would be super helpful if you share example of TFRecords that you try to use so that I could debug it.

**Comment by JCBrouwer** [comment]
Sadly the single GPU mode gives even less info:
```
[1]    56605 abort (core dumped)  CUDA_VISIBLE_DEVICES=0 python train_alae.py -c configs/flood-param.yaml
```

I've pushed the code I'm using to make the dataset here: https://github.com/JCBrouwer/ALAE/blob/master/dataset_preparation/images2tfrecords.py

I'll send you an email with a link to the tfrecords.

**Comment by dcnhan** [comment]
Hi, any update on this issue? 
I used **prepare_celeba_hq_tfrecords.py** to create the tfrecords. 
The tfrecords are generated smoothly without any problem.
However, when I started training, I got similar issue as @JCBrouwer 

```
2020-04-30 21:56:49,400 logger INFO: Trainable parameters generator:
2020-04-30 21:56:49,401 logger INFO: Trainable parameters discriminator:
2020-04-30 21:56:49,402 logger INFO: No checkpoint found. Initializing model from scratch
2020-04-30 21:56:49,402 logger INFO: Starting from epoch: 0
2020-04-30 21:56:49,474 logger INFO: ################################################################################
2020-04-30 21:56:49,474 logger INFO: # Switching LOD to 0
2020-04-30 21:56:49,474 logger INFO: # Starting transition
2020-04-30 21:56:49,474 logger INFO: ################################################################################
2020-04-30 21:56:49,474 logger INFO: ################################################################################
2020-04-30 21:56:49,474 logger INFO: # Transition ended
2020-04-30 21:56:49,474 logger INFO: ################################################################################
2020-04-30 21:56:49,475 logger INFO: Batch size: 64, Batch size per GPU: 64, LOD: 0 - 4x4, blend: 1.000, dataset size: 28992

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by podgorskiy** [comment]
Most likely, it is caused by a wrong path to tf records. 
Currently, there is a bug in DearBlopy, if it can not find the files, it crashes.
I'll be fixing it soon. Meanwhile double check that all  the paths are correct.

**Comment by LendelTheGreat** [comment]
I also had this issue when running train_alae.py after I created my own dataset using prepare_celeba_hq_tfrecords.py to create the tfrecords. 

My problem was that my original images were of various sizes.
Solved by resizing my images to 256x256 before passing them to prepare_celeba_hq_tfrecords.py

**Comment by podgorskiy** [comment]
The crash is fixed in https://github.com/podgorskiy/DareBlopy/commit/aadd8aaa189ef9b74f5b9c0d0d0a0a0e5a51ef46
Please update **dareblopy** package

**Comment by zhang-zx** [comment]
I used `pip install dareblopy` to reinstall dareblopy. However, after reinstallment, the problem still exists, and I make sure the path to tfrecords I created by `python dataset_preparation/prepare_celeba_hq_tfrecords.py` is correct.

**Comment by tousse-ensemble** [comment]
Hi, same problem here. Thanks in adavnace for your help!

**Comment by leopolddavid** [comment]
Same problem here!

**Comment by edgarschnfld** [comment]
same here

**Comment by fmbao** [comment]
Same problem here!

**Comment by gkumbc** [comment]
Facing the same problem, any update on this?
